### PR TITLE
[WEBSITE-813] Removed asset version variable from secrets.yml

### PR DESCRIPTION
**Pull request by UsmanAfzal**
### [WEBSITE-813] Removed asset version variable from secrets.yml
* #### Now handled in pugin-component-rails

### CODE REVIEW

**Review by jakemulley — DISMISSED** [review]
I don't think this is going to work the way we want.

Imagine these two prototypes:
- parliament.uk-prototype
- committees-prototype

If both want to use separate versions of brands (e.g. two different versions of Pugin) but the same component library, they'd have to jump through a hoop of forking the component library to change the version specifically for the committees stuff to use a specific committees-branding version.

I don't think this is what we were going for?

**Comment by UsmanAfzal** [comment]
Pugin is a dependency to component-rails. There are versions that won't work because of how tightly coupled they are.

**Example:**
- parliament.uk-prototype [v0.1]
  - components-rails [v0.2]
    - pugin [v1.2.4]

- committees-prototype [v0.1]
  - components-rails [v0.2]
    - pugin [v1.2.3]

In this example committees will not display the logo correctly because of markup amends that were made.

We will be using versioning for deployments (currently only on pugin). This means a new release to pugin will require a new release to pugin-components-rails that will require a new release to the application if we want it deployed. This ensures there is always a stable release.

You can also for debugging change the version in your local environment

**Comment by jakemulley** [comment]
Whilst Pugin is currently a dependency used by component-rails, it is also a dependency used by prototypes themselves. This will become an issue as soon as we start building other prototypes that rely on component-rails and pugin.

Our current setup is this:
- parliament.uk-prototype (backend)
	- components-rails (html)
	    - pugin (styling, branding)

It may become:
- parliament.uk-prototype (backend and custom HTML elements not componentised)
	- components-rails (html)
		- pugin (styling, branding)

For instance:
- parliament.uk-prototype contains the following:
    - ```<span class="icon"><i class="icon--arrow">Arrow</i></span>```

- parliament.uk-prototype holds the styling for this, since it doesn't need to be a component as it isn't used elsewhere:
    - ```.icon .icon--arrow { background-color: orange }```

Then, in an unrelated change, Pugin has this added:
- ```.icon .icon--arrow { padding: 48px }```

So, we have two things to think about here:
- Pugin and component-rails should have the same version available as Pugin will reflect markup changes in component-rails, which is fine
- Pugin and component-rails shouldn't _always_ be require using the same version.

We should adopt the SEMVER versioning system; ensuring minor and patch versions are backwards compatible for both Pugin and component-rails; and new versions of Pugin shouldn't also require a new version of component-rails.

Also imagine this scenario:
Pugin is updated with a hotfix because a background colour needs changing. Do you want a user to update component-rails too if it's just a style change?

**Review by mattrayner — APPROVED** [review]
Taken off line and approved

**Pull request merged**
